from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch
from reportlab.lib.colors import darkblue, red, green
from reportlab.lib.styles import ParagraphStyle
import datetime
import os


def generate_pdf_report(prediction, confidence, image_path):
    """
    Generate a professional PDF report for the AI Pneumonia Detection System.
    """

    filename = "Pneumonia_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        alignment=TA_CENTER,
        textColor=darkblue,
        fontSize=22,
        spaceAfter=20
    )

    heading_style = styles["Heading2"]

    normal_style = styles["BodyText"]

    story = []

    # -------------------------------
    # TITLE
    # -------------------------------

    story.append(
        Paragraph(
            "AI Pneumonia Detection Report",
            title_style
        )
    )

    story.append(
        Paragraph(
            f"<b>Date:</b> {datetime.datetime.now().strftime('%d-%m-%Y %H:%M')}",
            normal_style
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    # -------------------------------
    # RESULT
    # -------------------------------

    story.append(
        Paragraph(
            "Prediction Result",
            heading_style
        )
    )

    if prediction.upper() == "PNEUMONIA":

        result = f'<font color="red"><b>{prediction}</b></font>'

    else:

        result = f'<font color="green"><b>{prediction}</b></font>'

    story.append(
        Paragraph(
            f"Prediction: {result}",
            normal_style
        )
    )

    story.append(
        Paragraph(
            f"Confidence Score: <b>{confidence:.2f}%</b>",
            normal_style
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    # -------------------------------
    # X-RAY IMAGE
    # -------------------------------

    if image_path and os.path.exists(image_path):

        story.append(
            Paragraph(
                "Uploaded Chest X-Ray",
                heading_style
            )
        )

        img = Image(image_path)

        img.drawWidth = 4 * inch
        img.drawHeight = 4 * inch

        story.append(img)

        story.append(Spacer(1, 0.25 * inch))

    # -------------------------------
    # RECOMMENDATION
    # -------------------------------

    story.append(
        Paragraph(
            "Recommendation",
            heading_style
        )
    )

    if prediction.upper() == "PNEUMONIA":

        recommendation = """
The AI model detected findings that may be consistent with pneumonia.
Please consult a qualified physician or radiologist for further evaluation.
Additional clinical tests may be required before confirming a diagnosis.
"""

    else:

        recommendation = """
The AI model did not detect signs suggestive of pneumonia.
If symptoms such as fever, cough, chest pain, or breathing difficulty persist,
please seek medical advice.
"""

    story.append(
        Paragraph(
            recommendation,
            normal_style
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    # -------------------------------
    # DISCLAIMER
    # -------------------------------

    story.append(
        Paragraph(
            "Medical Disclaimer",
            heading_style
        )
    )

    disclaimer = """
This report has been generated using an Artificial Intelligence model
(DenseNet121) and is intended for educational and research purposes only.

It should not be used as a substitute for professional medical diagnosis,
clinical judgment, or treatment decisions.
"""

    story.append(
        Paragraph(
            disclaimer,
            normal_style
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
            "<b>Generated by AI Pneumonia Detection System</b>",
            normal_style
        )
    )

    doc.build(story)

    return filename